### ISSUE TITLE
Unwanted scrollbar

### ISSUE THREAD

**Issue by ligi** [ethereum/ethereum-foundation-website#25]
I guess this scrollbar is not wanted?:

![Selection_372](https://user-images.githubusercontent.com/111600/77239310-b4959a80-6bd9-11ea-8fb0-bc4e625271bd.png)

**Comment by samajammin** [comment]
Thanks for reporting this @ligi! FYI this bug looks to be on ethereum.org, which code lives here:
https://github.com/ethereum/ethereum-org-website

I believe this issue was solved in a recent PR:
https://github.com/ethereum/ethereum-org-website/pull/867

I'm going to close this out but please let us know if the issue persists!
